trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'

- script: |
    dotnet tool install --global dotnet-templating
    dotnet new --list
  displayName: 'Install .NET templates'

- task: DotNetCoreCLI@2
  inputs:
    command: 'new'
    arguments: 'console -n MyTestApp'
  displayName: 'Create new .NET Core console app'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'MyTestApp/MyTestApp.csproj'
  displayName: 'Restore packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MyTestApp/MyTestApp.csproj'
  displayName: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'MyTestApp/MyTestApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    testRunTitle: 'Unit tests'
  displayName: 'Run unit tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--no-build --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Publish artifacts'
  condition: succeededOrFailed()