trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '10.x'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'

- task: SnykTask@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    command: 'test'
    flags: '--severity-threshold=high'
    workingDir: '$(System.DefaultWorkingDirectory)'