trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitClone@2
  inputs:
    repository: 'https://github.com/snyk/nodejs-sample-app'
    clean: true
    checkoutSubmodules: false
    persistCredentials: true
  displayName: 'Clone GitHub repository'

- task: CmdLine@2
  inputs:
    script: 'cd $(Build.Repository.LocalPath) && npm init -y'
  displayName: 'Create package.json file'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: '<your_snyk_service_connection>'
    command: 'test'
    flags: '--severity-threshold=high'
    file: 'package.json'
  displayName: 'Run Snyk Security Scan'