trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '10.x'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    flags: '--severity-threshold=high'
    workingDir: '$(System.DefaultWorkingDirectory)'