trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: dir $(Build.SourcesDirectory)

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    testType: 'app'
    severityThreshold: 'high'
    monitorWhen: 'always'
    failOnIssues: true